# Generated by Django 5.2 on 2025-05-27 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="google_maps_url",
            field=models.URLField(
                blank=True,
                help_text="Optional: Link to this specific place on Google Maps",
            ),
        ),
    ]
