# Generated by Django 5.2 on 2025-05-27 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_location_google_maps_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="CampusCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("emoji", models.CharField(max_length=5)),
                ("description", models.TextField()),
                ("url_name", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
