# Generated by Django 5.2 on 2025-05-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_campuscategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="campuscategory",
            name="button_value",
            field=models.CharField(default="", max_length=50),
        ),
    ]
