# Generated by Django 5.2 on 2025-05-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_campuscategory_button_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("stationery", "Stationery"),
                            ("food", "Food & Snacks"),
                            ("printing", "Printing"),
                            ("general", "General Store"),
                            ("others", "Others"),
                        ],
                        default="others",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("owner", models.CharField(blank=True, max_length=100)),
                ("mobile_number", models.CharField(blank=True, max_length=20)),
                ("google_maps_url", models.URLField(blank=True)),
            ],
        ),
    ]
