# Generated by Django 5.2 on 2025-05-28 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_shop"),
    ]

    operations = [
        migrations.AddField(
            model_name="shop",
            name="location_note",
            field=models.TextField(
                blank=True, help_text="E.g. Near Hostel B main gate"
            ),
        ),
        migrations.AddField(
            model_name="shop",
            name="opening_hours",
            field=models.CharField(
                blank=True, help_text="e.g. 9AM - 7PM", max_length=100
            ),
        ),
    ]
