# Generated by Django 5.2 on 2025-05-29 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_shop_location_note_shop_opening_hours"),
    ]

    operations = [
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("auditorium", "Auditorium"),
                            ("adventure", "Adventure Spot"),
                            ("bank", "Bank and ATM"),
                            ("health", "Health Center"),
                            ("parking", "Parking Area"),
                            ("faculty", "Faculty Room"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("mobile_number", models.CharField(blank=True, max_length=50)),
                ("opening_hours", models.CharField(blank=True, max_length=100)),
                ("location_note", models.TextField(blank=True)),
                ("google_maps_url", models.URLField(blank=True)),
                ("more_info_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("capacity", models.IntegerField(blank=True, null=True)),
                ("has_projector", models.BooleanField(default=False)),
                ("sound_system_brand", models.CharField(blank=True, max_length=100)),
                ("ifsc_code", models.CharField(blank=True, max_length=20)),
                ("branch_code", models.CharField(blank=True, max_length=20)),
                ("atm_available", models.BooleanField(default=False)),
                ("faculty_name", models.CharField(blank=True, max_length=100)),
                ("department", models.CharField(blank=True, max_length=100)),
                ("office_hours", models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name="shop",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="shop",
            name="type",
            field=models.CharField(
                choices=[
                    ("stationery", "Stationery"),
                    ("food", "Food & Snacks"),
                    ("printing", "Printing"),
                    ("general", "General Store"),
                    ("others", "Others"),
                    ("mess", "Mess"),
                ],
                default="others",
                max_length=20,
            ),
        ),
    ]
