# Generated by Django 5.2 on 2025-05-31 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_facility_alter_shop_mobile_number_alter_shop_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("cse", "Computer Science and Engineering"),
                            ("electrical", "Electrical Engineering"),
                            ("civil", "Civil Engineering"),
                            ("mechanical", "Mechanical Engineering"),
                            ("chemical", "Chemical Engineering"),
                            ("materials", "Materials Engineering"),
                            ("biosciences", "Biological Sciences and Bioengineering"),
                            ("maths", "Mathematics"),
                            ("physics", "Physics"),
                            ("chemistry", "Chemistry"),
                            ("humanities", "Humanities and Social Sciences"),
                            ("earth", "Earth Sciences"),
                            ("cognitive", "Cognitive and Brain Sciences"),
                            ("design", "Design"),
                            ("other", "Staff/Other"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Designation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        choices=[
                            ("professor", "Professor"),
                            ("associate_professor", "Associate Professor"),
                            ("assistant_professor", "Assistant Professor"),
                            ("visiting_faculty", "Visiting Faculty"),
                            ("adjunct_professor", "Adjunct Professor"),
                            ("emeritus_professor", "Emeritus Professor"),
                            ("postdoc", "Postdoctoral Fellow"),
                            ("research_staff", "Research Staff"),
                            ("teaching_assistant", "Teaching Assistant"),
                            ("admin_staff", "Administrative Staff"),
                            ("director", "Director"),
                            ("dean", "Dean"),
                            ("hod", "Head of Department"),
                            ("warden", "Warden"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("personal_website", models.URLField(blank=True, null=True)),
                ("bio", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name="facility",
            name="mobile_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="facility",
            name="type",
            field=models.CharField(
                choices=[
                    ("auditorium", "Auditorium"),
                    ("adventure", "Adventure Spot"),
                    ("bank", "Bank and ATM"),
                    ("health", "Health Center"),
                    ("parking", "Parking Area"),
                    ("faculty", "Faculty Room"),
                    ("sports", "Sports"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "office_location",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "accessibility_info",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("office_notes", models.TextField(blank=True, null=True)),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.department",
                    ),
                ),
                (
                    "designation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.designation",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roles",
                        to="core.person",
                    ),
                ),
            ],
        ),
    ]
